version: '3.8'

services:
  scrapemaster:
    build: 
      context: ..
      dockerfile: deployment/Dockerfile
    container_name: scrapemaster
    restart: unless-stopped
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
    volumes:
      - ./logs:/var/log/nginx
    networks:
      - scrapemaster-network

  # Optional: Add a reverse proxy with SSL
  nginx-proxy:
    image: nginx:alpine
    container_name: nginx-proxy
    restart: unless-stopped
    ports:
      - "443:443"
    volumes:
      - ./ssl:/etc/nginx/ssl
      - ./proxy.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - scrapemaster
    networks:
      - scrapemaster-network

networks:
  scrapemaster-network:
    driver: bridge

volumes:
  logs: